### ISSUE TITLE
[NumberGuesser] "q".Equals(str)

### ISSUE THREAD

**Issue by pavel-b-novikov** [kir55rus/nsudotnet#2]
Ну что это такое? Почему вы пишете так? Объясните почему в .NET надо писать по-другому?

**Comment by kir55rus** [comment]
Привычка с Java
Исправил
В данном случае можно использовать оператор ==, так как на этапе компиляции известно, что оба операнда - строки. То есть, сравниваться будет именно содержимое, а не ссылки

**Comment by pavel-b-novikov** [comment]
А то есть в Java в таких случаях неизвестно что оба операнда - строки, нет?

**Comment by kir55rus** [comment]
В Java нет перегрузки операторов. Вот собственно кусок из сорцов класса string:
public static bool operator == (String a, String b) {
           return String.Equals(a, b);
        }

        public static bool operator != (String a, String b) {
           return !String.Equals(a, b);
        }

Оператор - статический метод. А значит на этапе компиляции необходимо знать, что оба операнда - строки, чтобы вызвать именно этот статический метод из класс строк

**Comment by pavel-b-novikov** [comment]
Ну вот это уже ближе к правде, да
